Hakkımızda sayfası eklenildi Layout Navigasyon değiştirildi
!!!!!Önemli-
Severity Code Description Project File Line Suppression State
Error CS0246 The type or namespace name 'ErrorViewModel' could not be found (are you missing a using directive or an assembly reference?) Trial Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Views_Shared_Error_cshtml.g.cs 18 Active

Hatası Gelmeye Başladı